version: '3.8'

services:
  frontend:
    build:
      context: ../tasks-assignment-app
      dockerfile: Dockerfile
    container_name: frontend_app
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - mongo
    environment:
      DATABASE_URL: postgres://myuser:mypassword@postgres:5432/mydb
      MONGO_URL: mongodb://mongo:27017/mydb
      JWT_SECRET: mysecretkey

  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data:
